# This ansible playbook brings up the world according to host groups in inventory file

- hosts: all-hosts
  user: "{{ ansible_ssh_user }}"
  gather_facts: false
  tasks:
  - include: tasks_check_ssh.yml

- hosts: all-hosts
  user: "{{ ansible_ssh_user }}"
  sudo: yes
  gather_facts: true
  vars:
     public_dns: ["8.8.8.8", "8.8.4.4"]
     masters_str: |
        {% set comma = joiner(",") %}
        {% set eth = "ansible_"+vpc_if %}
        {% for item in groups["masters"] -%}
            {{ comma() }}{{ hostvars[item][eth].ipv4.address }}
        {%- endfor %}

  pre_tasks:
  - include: pre_tasks_all_hosts.yml

  roles:
    - role: ansible-swap
      swap_file_size: "{{ ansible_memtotal_mb }}M"
      when: hostvars[inventory_hostname].ansible_swaptotal_mb < hostvars[inventory_hostname].ansible_memtotal_mb//2
    - role: ansible-docker
      docker_opts: '"-s devicemapper --registry-mirror=http://docker-proxy.service.consul:5001 --insecure-registry docker-registry.service.consul:5000"'
    - role: ansible-consul
      dns_nameservers: "{{ ['127.0.0.1', '8.8.8.8', '8.8.4.4'] if inventory_hostname in groups['masters'] else masters }}"
      dns_domain: "node.consul"
      consul_is_server: "{{ inventory_hostname in groups['masters'] }}"
      install_bind: "{{ inventory_hostname in groups['masters'] }}"
      consul_is_ui: "{{ inventory_hostname in groups['masters'] }}"
      consul_port_http: "8500"
      consul_domain: "consul."
      consul_port_dns: "8600"
      consul_client_address: "{{ '0.0.0.0' if inventory_hostname in groups['masters'] else local_ip }}"
      consul_bind_address: "{{ local_ip }}"
      consul_servers: "{{ masters }}"
    - role: ansible-beats
      when: inventory_hostname not in groups["masters"]
    - role: pintostack-docker-proxy
      when: inventory_hostname == "master-1"
    - role: pintostack-docker-registry
      when: inventory_hostname == "master-1"
    - role: ansible-nginx
      nginx_worker_processes: 1
      nginx_remove_default: yes
      nginx_sites:
      - id: docker-registry
        add_webroot: yes
        name: "docker-registry.consul.service"
      when: inventory_hostname == "master-1"
