options:
  resource-provider:
    type: string
    default: "aws"
    description: "Resource provider"

  vpc-if:
    type: string
    default: "eth0"
    description: "VPC Network IF name usualy eth1 but for AWS eth0"

  resource-provider-config:
    type: string
    default: |
        AWS_KEY_ID=AKIAI5asgdfgdfsgsgMUAZQ
        AWS_ACCESS_KEY=9dfsklbjklgjfdlgbjdlsbgjdslbgj
        AWS_KEY_ID=AKIAkljdfsgjkldf7NKAMUAZQ
        AWS_ACCESS_KEY=9MdfgdfklgjkldfjgklfdjgkldfsjglU8x/wW8N8uz
        AWS_KEYPAIR_NAME=PintoStack
        AWS_ROOT_PARTITION_SIZE=20
        AWS_AMI=ami-5189a661
        AWS_INSTANCE_TYPE=t2.micro
        AWS_REGION=us-west-2
        AWS_SECURITY_GROUPS='default,allow-ssh'
        AWS_SSH_USERNAME=ubuntu
        AWS_TERMINATE_ON_SHUTDOWN=true

    description: "Resource provider configuration content /pintostack/conf/source.* more [examples](https://github.com/pintostack/core/tree/master/conf)"

  masters-number:
    type: int
    default: 1
    description: "Number of MESOS master hosts to deploy"

  slaves-number:
    type: int
    default: 2
    description: "Number of MESOS slave hosts to deploy"

  ssh-private-key:
    type: string
    default: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpQIBAAKCAQEA4s9/wZS02ds3AYO2j+riPAxIdD8KTe7Em4okE7VE8P5hwxmT94wFVNs11JP6
      MIIEpQIBAAKCAQEA4s9/wZS02ds3AYO2j+riPAxIdD8KTe7Em4okE7VE8P5hwxmT94wFVNs11JP6
      C2GfAg+sGHZzzty5ooPnBhpfMuLsWcWLrf3LpCelYzFl1XG+2ZSLX5O1rA5oLV6INHQIOjDhCQ46
      MV1HydJhlBHPMGxhGGtc2X1kBjiyXoMiOTkyGEE+kzLBv9Ea0BxLJmnXbQ5eeWaMcrBPWMm38IgW
      Ehn6owHr+UQPS+qOunI4xhz6Af1p60ahiCP8By52JiQEQY0htrHOCQIDAQABAoIBAQCTqJb5xgA/
      ns/XNeRvu5IDrMVaczFy6pHCHWpisPCiioj0WkBh0AQ11rzRk43zAph81tPyii+gizJ0jxPmZn1i
      ns/XNeRvu5IDrMVaczFy6pHCHWpisPCiioj0WkBh0AQ11rzRk43zAph81tPyii+gizJ0jxPmZn1i
      ns/XNeRvu5IDrMVaczFy6pHCHWpisPCiioj0WkBh0AQ11rzRk43zAph81tPyii+gizJ0jxPmZn1i
      ns/XNeRvu5IDrMVaczFy6pHCHWpisPCiioj0WkBh0AQ11rzRk43zAph81tPyii+gizJ0jxPmZn1i
      eSgiiIfjjwEjhv8zZo0YilVzFsYBAoGBAPpVGK7KzMLWhkKQ3MD5W4QUjSrWziTY77OUy5VmjKd1
      YN8bdkK3AVImD+nY9SFk+GmZdS9gL9bOqkLLsyeaNXEknb+nY5ancDmTWN4okQhDVB8k0guqVQ1m
      MIIEpQIBAAKCAQEA4s9/wZS02ds3AYO2j+riPAxIdD8KTe7Em4okE7VE8P5hwxmT94wFVNs11JP6
      7qDleHzls5NRyVQd28H5/N7VFsZk7OizDlbQWZkUq6CuHaTK1gNiIe2NkykMaMl31AXYLGdoO0CJ
      nHy4lNoMPujarCIm0lMNCkvMErEOL7XbitMpww0h1ynhK/VO2sjWFyBO12ZHmg2HI/p7jRktBfOp
      SJmfLZm00HooXgXPwEtHTNmmNPLctfZj+eLCoxkE3x4n8OVvyT4vuxq0eEmCoUFN0duqxPjYMBv8
      SIlozAeUGf9qxNm9AoL+dksW8S6bLryudqPAIvePgiYxwg0LsSLc/elUBVf4STJjwHqR7xDVxB8d
      Yp63azmgEaAaF6OdCsZ0egsBAoGAHbYRjPKXH3m7L2+udfpXmv6qB325Ghbw7jiA7QEj1jt/llxZ
      SJmfLZm00HooXgXPwEtHTNmmNPLctfZj+eLCoxkE3x4n8OVvyT4vuxq0eEmCoUFN0duqxPjYMBv8
      GpSL3O7NkIIUOMYiRmMafX2HKtlOmEh1wGPeRPjMozv0NjkCgYEAsFMcem96a2Acezf7XfBEiqDD
      SJmfLZm00HooXgXPwEtHTNmmNPLctfZj+eLCoxkE3x4n8OVvyT4vuxq0eEmCoUFN0duqxPjYMBv8
      fjvldfjsvklfjdlbvkjdfklsbjkldgfjbgklfjbklgfjbklfdjkgfjbkldbj
      -----END RSA PRIVATE KEY-----

    description: "Put here the content of .pem or id_rsa file"

  ssh-publick-key:
    type: string
    default: |
      -----BEGIN RSA PUBLIC KEY-----
      fjvldfjsvklfjdlbvkjdfklsbjkldgfjbgklfjbklgfjbklfdjkgfjbkldbjfj
      vldfjsvklfjdlbvkjdfklsbjkldgfjbgklfjbklgfjbklfdjkgfjbkldbjfggf
      vldfjsvklfjdlbvkjdfklsbjkldgfjbgklfjbklgfjbklfdjkgfjbkldbjfggf
      vldfjsvklfjdlbvkjdfklsbjkldgfjbgklfjbklgfjbklfdjkgfjbkldbjfggf
      vldfjsvklfjdlbvkjdfklsbjkldgfjbgklfjbklgfjbklfdjkgfjbkldbjfggf
      -----END RSA PUBLIC KEY-----

    description: "Put here the content of .pem or id_rsa.pub file"
