consul_playbook_version: "0.1.0"

# Packages per version, system and architecture
consul_packages:
  0.5.2:
    Darwin:
      x86_64: 
        name: '0.5.2_darwin_amd64.zip'
        sha256sum: '87be515d7dbab760a61a359626a734f738d46ece367f68422b7dec9197d9eeea'
    Linux:
      x86:
        name: '0.5.2_linux_386.zip'
        sha256sum: '29306ce398109f954ceeea3af79878be4fb0d949f8af3a27c95ccef2101e8f60'
      amd64:  
        name: '0.5.2_linux_amd64.zip'
        sha256sum: '171cf4074bfca3b1e46112105738985783f19c47f4408377241b868affa9d445'
      x86_64:
        name: '0.5.2_linux_amd64.zip'
        sha256sum: '171cf4074bfca3b1e46112105738985783f19c47f4408377241b868affa9d445'

consul_webui_packages:
  0.5.2:
    name: 0.5.2_web_ui.zip
    sha256sum: ad883aa52e1c0136ab1492bbcedad1210235f26d59719fb6de3ef6464f1ff3b1   

